services:
  filestash:
    image: machines/filestash:latest
    container_name: filestash
    restart: always
    environment: {}
    volumes:
      - filestash:/app/data/state/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filestash.rule=Host(`filestash.martin-linde.com`)"
      - "traefik.http.routers.filestash.entrypoints=websecure"
      - "traefik.http.services.filestash.loadbalancer.server.port=8334"
volumes:
  filestash:
